import { iCollection, iCollectionContent } from "../interface/collection.interface";

export const collections: iCollection[] = [
    {
        thumbnail: 'sliderimg1.png',
        author: {
            title: 'Krill',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    },
    {
        thumbnail: 'sliderimg2.png',
        author: {
            title: 'Jellyfish',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    },
    {
        thumbnail: 'sliderimg3.png',
        author: {
            title: 'Geoduck',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    },
    {
        thumbnail: 'sliderimg4.png',
        author: {
            title: 'Sedna',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    },
    {
        thumbnail: 'sliderimg5.png',
        author: {
            title: 'Namora',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    },
    {
        thumbnail: 'sliderimg6.png',
        author: {
            title: 'Marrina Smallwood',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    },
    {
        thumbnail: 'sliderimg10.png',
        author: {
            title: 'Stingray',
            name: 'MAWC',
            thumb: 'Ellipse 6.png'
        },
        price: '80 SHM',
        bidRate: '7.59 wSHM'
    }
];


export const collectionContents: iCollectionContent = {
    title: 'Mutant Aquatic Warriors Club NFTs',
    content: 'Earn crypto  by holding MAWC. We genuinely stick to the mantra of HODL & help you earn up to 20% in the Shardeum (SHM) tokens from the fees generated by our upcoming NFT Marketplace Shardible.'
}